# Repo: MySpace/TemplateRepo
# File: azure-pipeline.yml
# make changes
# make 2nd changes
# make 3rd changes
# made 4rth changes
# made 5th changes
# made 6th changes
# made 7th changes
# 8th
# 9th
# 10th
name: cicd_ci

# trigger:
#   branches:
#     include:
#       - master

stages:
- stage: CI_Checks
  jobs:
  - job:
    displayName: yamllint_checks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install yamllint
        yamllint -d "{extends: relaxed, rules: {line-length: {max: 200}, new-line-at-end-of-file: disable, new-lines: disable}}" .
      displayName: 'YAML Lint Checks'
